[package]
name = "tlbb_spl_token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
solana-program = "1.17.0"
log = "0.4"
thiserror = "1.0"

[features]
default = ["no-entrypoint"]
no-entrypoint = []